sudo: required
language: node_js
services:
  - docker
node_js:
- '8'
env:
  global:
  - SAUCE_USERNAME=elastic-apm-base
  - SAUCE_ACCESS_KEY=4b6720f1-ecdc-448d-85be-ebf947e14507
  - APM_SERVER_PORT=8001
  - APM_SERVER_URL=http://localhost:8001
  - MODE=saucelabs
  matrix:
  - STACK_VERSION=7.0.0-alpha1-SNAPSHOT APM_SERVER_BRANCH=v2 APM_SERVER_REPO=elastic/apm-server
cache:
  directories:
  - node_modules
addons:
  firefox: '57.0'
  chrome: stable
  apt:
    packages:
     - xsltproc
     - libxml2-utils
before_install:
  - docker-compose -f ./test/docker-compose.yml up -d apm-server-dev
before_script:
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3